### PR TITLE
Allow setting the GitHub API URL from an environment variable

### PR DESCRIPTION
**Pull request by asonas**
Hi.
I was unable to execute this action on GitHub Enterprise because the GitHub URL was hardcoded. 
To make this GitHub Action available from sources other than github.com, I will make changes to allow the URL to be modified via environment variables.
Also, the hardcoded URL includes a path (/repos). In this method, I have made changes to only return the hostname and extract the path (/repos) to where it is being called.

### CODE REVIEW

**Comment by asonas** [comment]
@joshmfrankel Could you review these changes?

**Comment by joshmfrankel** [comment]
Fantastic change. Looking at why CI failed currently, looks to be permission issue

**Comment by joshmfrankel** [comment]
I was able to finally come back around to this. Looks like there were several test failures due external http requests made in the test suite. Should be an easy fix though you may need to look into using ClimateControl for dealing with the EnvVar

``` ruby
rspec ./specs/integration/integration_spec.rb:46 # Check Action integration for coverage type line for Pushes Fails when coverage is lower than suite minimum
rspec ./specs/integration/integration_spec.rb:162 # Check Action integration for coverage type line for Pushes when SimpleCov-json coverage file is present Fails when coverage is lower than file minimum and prints failing files
rspec ./specs/integration/integration_spec.rb:200 # Check Action integration for coverage type line for Pushes when SimpleCov-json coverage file is present Fails when fallback suite minimum coverage fails
rspec ./specs/integration/integration_spec.rb:232 # Check Action integration for coverage type line for Pull Requests Fails when coverage is lower than minimum
```

**Review by joshmfrankel — CHANGES_REQUESTED** [review]
Fix tests for external HTTP calls and we should be good to go 🚀

**Comment by joshmfrankel** [comment]
I believe that https://github.com/joshmfrankel/simplecov-check-action/pull/20 satisfied the request here on the failing tests. I'm going to close this one out. We could still use an update to the README.md

**Pull request closed without merging**
